on:
  workflow_dispatch:
    inputs:
      ReleaseType:
        description: 'Release Type'
        required: true
        default: 'warning'
        type: choice
        options:
        - major
        - feature
        - bug
  push:
    branches:
      - dev

jobs:
  RELEASE:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git tag | sort -V | tail -1

  tagging:
    runs-on: ubuntu-latest
    steps:
    - name: Bump release version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.3
      with:
        current-version: '0.0.1'
        version-fragment: ${{ inputs.ReleaseType }}
    - name: Do something with your bumped release version
      run: echo ${{ steps.bump_version.outputs.next-version }}
      # will print 2.12.0
