name: Non Production Release
on:
  push:
    branches:
    - dev
    - sta
  create:
    tags:        
      - '*'

jobs:
  # Preparing the build environment variables
  prepare-env:
    name: Prepare Env
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - id: vars
      run: |
        echo "build success"
