on:
  workflow_dispatch:
    inputs:
      ReleaseType:
        description: 'Release Type'
        required: true
        default: 'warning'
        type: choice
        options:
        - Major
        - Feature
        - Bug
      ReleaseNote:
        description: 'Release Note'
        required: true

jobs:
  RELEASE:
    runs-on: ubuntu-latest
    steps:
     - id: PreValidation 
       run: |
        BRANCH="${GITHUB_REF#refs/heads/}"
        if [ $BRANCH == 'main' ]
        then
          echo "Branch validation Successful "      
        else
          echo "Releases only taken from main branch"
          exit 1
        fi
     - id: releasetype
       uses: ASzc/change-string-case-action@v5
       with:
        string: ${{ inputs.ReleaseType }}
     - uses: actions/checkout@main
       with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
     - name: 'Get Previous tag'
       id: previoustag
       uses: "WyriHaximus/github-action-get-previous-tag@v1"
       with:
        fallback: 0.0.1 # Optional fallback tag to use when no tag can be found
     - name: Bump release version
       id: bump_version
       uses: christian-draeger/increment-semantic-version@1.0.3
       with:
        current-version: ${{ steps.previoustag.outputs.tag }}
        version-fragment: ${{ steps.releasetype.outputs.lowercase }}
     - name: Do something with your bumped release version
       run: echo ${{ steps.bump_version.outputs.next-version }}

     - name: push new version tag
       uses: actions/checkout@v3
     - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.bump_version.outputs.next-version }}
          git push origin ${{ steps.bump_version.outputs.next-version }}
     - name: "Build Changelog"
       id: build_changelog
       uses: mikepenz/release-changelog-builder-action@v3.4.0
       with:
        configurationJson: |
          {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                    "title": "## 💬 Other",
                    "labels": ["other"]
                },
                {
                    "title": "## 📦 Dependencies",
                    "labels": ["dependencies"]
                }
              ]
            }
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     - name: Create Release
       id: create_release
       uses: actions/create-release@v1
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
       with:
         tag_name: ${{ steps.bump_version.outputs.next-version }}
         release_name: Release V.${{ steps.bump_version.outputs.next-version }}
         body: |
            ${{steps.github_release.outputs.changelog}}
         draft: false
         prerelease: false
