on:
  workflow_dispatch:
    inputs:
      ReleaseType:
        description: 'Release Type'
        required: true
        default: 'warning'
        type: choice
        options:
        - major
        - feature
        - bug
      ReleaseNote:
        description: 'Release Type'
        required: true

jobs:
  RELEASE:
    runs-on: ubuntu-latest
    steps:
     - run: |
        BRANCH="${GITHUB_REF#refs/heads/}"
        if [ $BRANCH == 'main' ]
        then
          echo "Branch validation Successful "      
        else
          echo "Branch not configured!"
          exit 1
        fi
     - uses: actions/checkout@main
       with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
     - name: 'Get Previous tag'
       id: previoustag
       uses: "WyriHaximus/github-action-get-previous-tag@v1"
       with:
        fallback: 0.0.1 # Optional fallback tag to use when no tag can be found
     - name: Bump release version
       id: bump_version
       uses: christian-draeger/increment-semantic-version@1.0.3
       with:
        current-version: ${{ steps.previoustag.outputs.tag }}
        version-fragment: ${{ inputs.ReleaseType }}
     - name: Do something with your bumped release version
       run: echo ${{ steps.bump_version.outputs.next-version }}

     - name: push new version tag
       uses: actions/checkout@v3
     - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.bump_version.outputs.next-version }}
          git push origin ${{ steps.bump_version.outputs.next-version }}
