name: Build & Deploy
on:
  workflow_dispatch:
  push:
    branches:
    - dev
    - sta
    tags:        
      - 'v.[0-9]+.[0-9]+.[0-9]+'

jobs:
  # Preparing the build environment variables
  prepare-env:
    name: Prepare Env
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - id: vars
      run: |
        echo "build success"
